### ISSUE TITLE
Ethereum is not orphan proof

### ISSUE THREAD

**Issue by sammy007** [sammy007/open-ethereum-pool#8]
I'll keep it here to refer if there will be complains regarding `lost` blocks.

![screen shot 2016-05-07 at 09 50 56](https://cloud.githubusercontent.com/assets/7374093/15090227/6371735a-1439-11e6-8032-ad2984770b52.png)

Related geth issue: https://github.com/ethereum/go-ethereum/issues/2298

Even if it `fixed` on 1.4 I found that geth is loosing uncles sometimes, this is how ETH works, it is not orphan proof.

**Comment by mmitech** [comment]
I woke up to two lost blocks and I was surprised, thanks for the explanation.

**Comment by sammy007** [comment]
You can update geth to 1.4, can reduce orphan rate, but I don't like its RAM usage tbh.

**Comment by mmitech** [comment]
Ram is not an issue for me, will do it now :)

**Comment by sammy007** [comment]
I am concerned about RAM usage spike because you never know to what profitability it leads :)

**Comment by kilo17** [comment]
Would this be the same issue, The first mined block 1,489,081 shows that I mined it but on the blockchain it shows F2Pool mined it and I got no ethereum from it. 
![Uploading image.jpeg…]()

**Comment by kilo17** [comment]
![image](https://cloud.githubusercontent.com/assets/6282390/15135041/84ed5b48-1637-11e6-9917-2d21064f7855.jpeg)

**Comment by clintar** [comment]
I tried to use the 1.4 tag and pool doesn't stay in sync with geth anymore

**Comment by mmitech** [comment]
Use  this one https://github.com/ethereum/go-ethereum/releases/tag/v1.4.2

**Comment by mmitech** [comment]
**Update: **  don't use The latest geth 1.4.2, it has issues https://github.com/ethereum/go-ethereum/issues/2536

**Comment by sammy007** [comment]
@ logged block number is not always true. Only block hash is true. Height and job is inconsistent and pool is logging what it has on a moment when block found.

**Comment by mmitech** [comment]
Fixed here https://github.com/ethereum/go-ethereum/pull/2537

**Comment by sammy007** [comment]
Still not orphan proof. There is no a single blockchain without orphans in this world. I am locking it now, it was just a notice to everyone.

FYI: Height logged for block in a pool is not always 100% correct. In other words block number 1024 can be actually 1023 or 1025. Not an issue, just how pool logs it (yet).
